### ISSUE TITLE
Broooo

### ISSUE THREAD

**Issue by EmmyMay** [mul1sh/easy-print#2]
Can I please have your email address? You are difficult to reach. I would love to talk to you about Gitcoin. Sorry, I will delete this issue as soon as you reply

**Comment by mul1sh** [comment]
Hey @EmmyMay sure, you can reach me at, mulili.nzuki [at] gmail [dot] com 🙂

**Comment by EmmyMay** [comment]
Hi. I did send an email. I want to confirm if you received my email.

**Comment by EmmyMay** [comment]
Hi


Sent from Mail for Windows 10

**Comment by mul1sh** [comment]
Hi @EmmyMay  sorry for the delay in answering been travelling the last 2 days.

Now yes I got our email and would very much love to collaborate in gitcoin. But as for that project, i'm almost finished with i.e. like 95% done. I actually need to just get some clarification on a few things from torus and I'll submit it later today or over the weekend. So yeah I don't know how we can go about it

**Comment by EmmyMay** [comment]
Thanks for replying. 

I have thought about it and this is how I think it can work:
	We can all apply to bounties that we feel we can go through individually and which isn’t drawing too much attention. If we do feel like we’ve got a bounty that is high paying and some extra effort will help reduce work-time, then we could collaborate. We could all apply for the bounty to maximize our chances of getting it and whoever gets the bounty gets to turn in the bounty and collect the pay. This person will then be responsible for sharing it down to others.

 we could have could have a multi-accessible GitHub account. Each person’s part can be given to them swiftly on either a discord server or whichever team collaboration software we decide on. 

Each coder would push a commit of their job and the final piece would be submitted.

I see team effort on gitcoin all the time. We just have to know our strengths and be honest about the jobs we can’t execute. I think you and the third person I reached out to are better coders than I and you understand the block chain.

I’m just getting into the block chain with JS. I won’t stand in your way if the job is past my skills. 

Let me know what you think.

Sent from Mail for Windows 10

**Comment by mul1sh** [comment]
@EmmyMay thanks for your reply, sounds great. Let me know then when you see bounties we should collaborate on especially for the hackathons.
